version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "📦 Installing dependencies"
      - npm install

  build:
    commands:
      - echo "🏗 Building for $REACT_APP_ENV environment"
      - npm run ${REACT_APP_ENV}-build
      - chmod +x scripts/*.sh
      - scripts/generate_appspec.sh

artifacts:
  files:
    - build/**/*      # Include the build output
    - appspec.yml     # Must be at root of zip
    - scripts/**/*    # Include lifecycle scripts if applicable
