version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "📦 Installing dependencies"
      - npm install

  build:
    commands:
      - echo "🏗 Building for $REACT_APP_ENV environment"
      - npm run ${REACT_APP_ENV}-build

artifacts:
  files:
    - '**/*'
  base-directory: build
