server {
    listen 80;
    server_name _;

    location ^~ /prod/ {
        alias /var/www/prod/public_html/;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location ^~ /stage/ {
        alias /var/www/stage/public_html/;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location ^~ /dev/ {
        alias /var/www/dev/public_html/;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /health {
        return 200 'OK';
        add_header Content-Type text/plain;
    }
}
